---
 - hosts: all
   become: yes
   become_user: root
 
   tasks:
    - name: update apt cache
      apt:
        update_cache: yes
        state: present

    - name: install awscli
      apt: 
        name: awscli
        state: present