all:
  hosts:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/myupgradec2new.cer
  children:
    bastion:
      hosts:
        54.166.33.146:
    jenkins:
      hosts:
        10.0.1.88:
    app:
      hosts:
        10.0.1.205: